-- Q1. Find the total revenue generated by each product category.
SELECT product_category, count(revenue) from sales
group by product_category;

-- Q2. Find the average revenue of each product category and arrange it from highest to lowest.
select product_category, avg(revenue) as avg_revenue from sales
group by product_category
order by avg_revenue desc ;

-- Q3. Find the total quantity sold by each product category in each region.
select product_category, sum(quantity) as total_quantity, region from sales
group by region,  product_category;

-- Q4. Find the region having the highest total revenue.
select region, round(sum(revenue)) as total_revenue from sales
group by region
order by total_revenue desc limit 1;

-- Q5. Find the payment method having the highest total revenue.
select * from sales;
select payment_method , round(sum(revenue)) as total_revenue from sales
group by payment_method
order by total_revenue desc limit 1;

-- Q6. Find the average customer rating for each region.
select  region, avg(customer_rating) as avg_rating from sales
group by region;

-- Q7. Find the product category having the highest average customer rating.
select product_category ,avg(customer_rating) as avg_rating from sales 
group by product_category
order by avg_rating desc limit 1;

-- Q8. Find the product category having the lowest average delivery time.
select * from sales;
select product_category, avg(delivery_days) as avg_delivery_time from sales
group by product_category
order by avg_delivery_time asc limit 1;

-- Q9. Find the total discount given in each product category.
select product_category, sum(discount) as total_discount from sales
group by product_category;

-- Q10. Find the average unit price for each product category.
select * from sales;
select product_category, avg(unit_price) from sales
group by product_category;